import streamlit as st
import joblib
import re
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from lime.lime_text import LimeTextExplainer
import streamlit.components.v1 as components

# 1. Setup and Page Config
st.set_page_config(page_title="AI vs Human Text Detector", layout="wide")
st.title("🤖 AI vs Human Text Detector")
st.markdown("This app uses a Machine Learning model to detect if a text was written by a Human or generated by AI, providing visual explanations for its decision.")

# 2. Load model components
# Note: If you saved your best_model as a Pipeline, it might already include the vectorizer.
@st.cache_resource
def load_model():
    model = joblib.load("F:/AI_Text_Detector/models/classifier.pkl")
    vectorizer = joblib.load("F:/AI_Text_Detector/models/vectorizer.pkl")
    return model, vectorizer

model, vectorizer = load_model()

# 3. Preprocessing Function (matches eda.ipynb logic)
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

# 4. Explainability Setup (LIME)
explainer = LimeTextExplainer(class_names=['AI', 'Human'])

def predict_probs(texts):
    # This function is required by LIME to see probability scores
    X = vectorizer.transform(texts)
    return model.predict_proba(X)

# 5. User Interface
user_input = st.text_area("Enter text to analyze:", height=200, placeholder="Paste your text here...")

if st.button("Analyze Text"):
    if user_input.strip() == "":
        st.warning("Please enter some text.")
    else:
        # Preprocessing
        cleaned_input = clean_text(user_input)
        X = vectorizer.transform([cleaned_input])
        
        # Prediction
        prediction = model.predict(X)[0]
        probabilities = model.predict_proba(X)[0]
        
        # Display Results
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("Result")
            if prediction == "AI":
                st.error(f"Prediction: **{prediction}**")
            else:
                st.success(f"Prediction: **{prediction}**")
            
            st.write(f"Confidence: {max(probabilities)*100:.2f}%")

        # --- VISUALIZATION PART (Word Cloud) ---
        with col2:
            st.subheader("Visualization: Word Cloud")
            wc = WordCloud(width=400, height=200, background_color='white').generate(cleaned_input)
            fig, ax = plt.subplots()
            ax.imshow(wc, interpolation='bilinear')
            ax.axis('off')
            st.pyplot(fig)

        st.divider()

        # --- EXPLAINABILITY PART (LIME) ---
        st.subheader("Explainability: Why did the model choose this?")
        st.info("The words highlighted in orange contribute to an 'AI' prediction, while blue words suggest 'Human' (colors may vary based on model classes).")
        
        with st.spinner("Generating explanation..."):
            # Generate LIME explanation
            exp = explainer.explain_instance(
                user_input, 
                predict_probs, 
                num_features=10
            )
            
            # Render LIME in Streamlit
            html_content = exp.as_html()
            components.html(html_content, height=800, scrolling=True)